name: "CI"
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  OTP_VERSION: 27.2
  ELIXIR_VERSION: 1.17.3

jobs:
  build_android:
    name: "Build Android Runtimes"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Install Dependencies
        run: mix deps.get

      - name: Build Android ${{ matrix.arch }} Runtimes
        run: |
          ARCH=${{ matrix.arch }} mix package.android.runtime
          ARCH=${{ matrix.arch }} mix package.android.nif

      - name: Archive Android Runtimes
        uses: actions/upload-artifact@v3
        with:
          name: android-${{ matrix.arch }}-runtime
          path: _build/${{ matrix.arch }}/*.zip

      - name: Publish Android Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/${{ matrix.arch }}/*.zip

  build_ios:
    name: "Build iOS Runtime"
    runs-on: macos-latest
    steps:
      - name: Install Prerequisites
        run: brew install git carthage coreutils

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Erlang and Elixir with asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
          echo ". $HOME/.asdf/asdf.sh" >> $HOME/.bash_profile
          . $HOME/.asdf/asdf.sh
          asdf plugin-add erlang || true
          asdf plugin-add elixir || true
          asdf install erlang ${{ env.OTP_VERSION }}
          asdf install elixir ${{ env.ELIXIR_VERSION }}
          asdf global erlang ${{ env.OTP_VERSION }}
          asdf global elixir ${{ env.ELIXIR_VERSION }}

      - name: Install Dependencies
        run: mix deps.get

      - name: Build iOS Runtime
        run: mix package.ios.runtime

      - name: Archive iOS Runtime
        uses: actions/upload-artifact@v3
        with:
          name: ios-runtime
          path: _build/liberlang.xcframework

      - name: Publish iOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/liberlang.xcframework
