name: "CI"
on: ["push", "pull_request", "workflow_dispatch"]
env:
  OTP_TAG: OTP-27.2
  OTP_SOURCE: https://github.com/erlang/otp

jobs:
  build:
    name: "Build Android runtimes"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        arch: ["arm", "arm64", "x86_64"]
    steps:
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2
          elixir-version: 1.17.3

      - uses: actions/checkout@v2

      - run: |
          scripts/install_elixir.sh "$HOME/elixir"
          echo "$HOME/elixir/bin" >> $GITHUB_PATH

      - name: Build Android ${{ matrix.arch }} runtimes
        run: |
          mix deps.get
          ARCH=${{ matrix.arch }} mix package.android.runtime
          ARCH=${{ matrix.arch }} mix package.android.nif
      - name: Archive Android runtimes
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}-runtime
          path: _build/*.zip
      - name: Android ${{ matrix.arch }} release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/*.zip

  ios:
    name: "Build iOS runtime"
    runs-on: "macos-latest"
    steps:
      - run: brew install git carthage coreutils
      - uses: actions/checkout@v2

      - name: Setup elixir
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf
          . $HOME/.asdf/asdf.sh
          asdf plugin add erlang
          asdf plugin add elixir
          echo "erlang 27.2" >> .tool-versions
          echo "elixir 1.17.3-otp-27" >> .tool-versions
          asdf install

      - name: Build runtime
        run: |
          . $HOME/.asdf/asdf.sh
          mix package.ios.runtime

      - name: Archive runtimes
        uses: actions/upload-artifact@v2
        with:
          name: iOS-runtime
          path: _build/liberlang.xcframework

      - name: iOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/liberlang.xcframework
